2025-04-13 12:47:17 - INFO - logger - <module> - Приложение запущено
2025-04-13 12:47:17 - INFO - logger - <module> - Добавляем логирование в остальные файлы проекта...
2025-04-13 12:47:17 - INFO - logger - <module> - Логирование в database.py: все запросы к серверу регистрируются.
2025-04-13 12:47:17 - INFO - logger - <module> - Логирование в COM.py: события работы с COM-портами фиксируются.
2025-04-13 12:47:17 - INFO - logger - <module> - Логирование в detail_work.py: операции с деталями регистрируются.
2025-04-13 12:47:17 - INFO - logger - <module> - Логирование в Error.py и ErrorTest.py: ошибки записываются.
2025-04-13 12:47:17 - INFO - logger - <module> - Логирование в этапах Mark.py, Packing.py, Test.py, Work.py.
2025-04-13 12:47:20 - INFO - logger - log_event - Сервер доступен
2025-04-13 12:47:20 - INFO - logger - log_event - Сервер доступен
2025-04-13 12:47:20 - INFO - logger - log_event - Главное окно приложения создано
2025-04-13 12:47:20 - ERROR - logger - log_error - Ошибка: Не найден подходящий COM-порт
NoneType: None
2025-04-13 12:47:20 - ERROR - logger - log_error - Ошибка: SerialManager не передан! COM-порт не будет работать.
NoneType: None
2025-04-13 12:47:20 - INFO - logger - log_event - Создан интерфейс админ-панели
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to mark
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to Test
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to Packing
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to Login page AA
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to assembly
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to mark
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to Test
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to Packing
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to Login page AA
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to assembly
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to mark
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to Test
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to Packing
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to Login page AA
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to assembly
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to mark
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to Test
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to Packing
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to Login page AA
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to assembly
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to mark
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to Test
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to Packing
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to Login page AA
2025-04-13 12:47:20 - INFO - logger - log_event - Enter to assembly
2025-04-13 12:47:25 - INFO - logger - log_event - Попытка аутентификации пользователя с UID: 636611317
2025-04-13 12:47:25 - INFO - logger - log_event - Запрос: {'type': 'user', 'uid': '636611317'}
2025-04-13 12:47:25 - ERROR - logger - log_error - Ошибка: Непредвиденная ошибка: type object 'datetime.datetime' has no attribute 'datetime'
Traceback (most recent call last):
  File "c:\Users\Gilaz\RFID-marks\RFID-marks\GUI\database.py", line 55, in database
    utc_time = datetime.datetime.utcnow()
               ^^^^^^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
2025-04-13 12:47:25 - INFO - logger - log_event - Ответ сервера: None
2025-04-13 12:47:43 - INFO - logger - log_event - Закрытие приложения button.py
2025-04-13 12:47:43 - INFO - logger - log_application_exit - Приложение завершено
